# Learning TensorFlow

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
import pandas as pd

# TensorFlow - Basics

In [4]:
# Tensor is multidimentional array or list

In [5]:
# Shape: The number of rows and columns together define the shape of Tensor.

In [6]:
# Type
# Type describes the data type assigned to Tensor’s elements.

# A user needs to consider the following activities for building a Tensor −

# Build an n-dimensional array
# Convert the n-dimensional array.

# Various Dimensions of TensorFlow
TensorFlow includes various dimensions. The dimensions are described in brief below −

# One dimensional Tensor
One dimensional tensor is a normal array structure which includes one set of values of the same data type.1

In [7]:
import numpy as np

In [8]:
tensor_1D = np.array([1,2,3,4,5,6,7,8,9], dtype = np.int)
tensor_2D = np.array([[1,2,3,4,5,6,7,8,9],
                     [12,12,23,34,34,65,34,32,43]
                     ], dtype = np.float64)

In [9]:
print(tensor_1D)
print(tensor_2D)

[1 2 3 4 5 6 7 8 9]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [12. 12. 23. 34. 34. 65. 34. 32. 43.]]
[1 2 3 4 5 6 7 8 9]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [12. 12. 23. 34. 34. 65. 34. 32. 43.]]


In [10]:
print(tensor_1D.shape)
print(tensor_1D.size)

(9,)
9
(9,)
9


In [11]:
print(tensor_1D.dtype)

int32
int32


In [12]:
print(tensor_2D.shape)
print(tensor_2D.size)

(2, 9)
18
(2, 9)
18


In [13]:
print(tensor_2D[0])
print(tensor_2D[1])

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[12. 12. 23. 34. 34. 65. 34. 32. 43.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[12. 12. 23. 34. 34. 65. 34. 32. 43.]


# Tensor Handling and Manipulations

In [14]:
matrix1 = np.array([[2,2,2],
                   [2,2,2],
                   [2,2,2]
                   ],dtype = np.int32)
matrix2 = np.array([[1,1,1],
                   [1,1,1],
                   [1,1,1]
                   ], dtype = np.int32)

In [15]:
print(matrix1)
print(matrix2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)

In [17]:
matrix_product = tf.matmul(matrix1,matrix2)
matrix_addition = tf.add(matrix1,matrix2)

In [18]:
print(matrix_product)
print(matrix_addition)

tf.Tensor(
[[6 6 6]
 [6 6 6]
 [6 6 6]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[6 6 6]
 [6 6 6]
 [6 6 6]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)


In [19]:
matrix3 = np.array([
    [1,2,3],
    [3,9,0.7],
    [2,5,9]
],dtype = np.float64)

In [20]:
print(matrix3)

[[1.  2.  3. ]
 [3.  9.  0.7]
 [2.  5.  9. ]]
[[1.  2.  3. ]
 [3.  9.  0.7]
 [2.  5.  9. ]]
